@startuml
'https://plantuml.com/state-diagram
participant 企业微信主页面 as main

participant 通讯录页面 as contact

participant 添加成员页面 as add_member

participant 添加部门页面 as add_department

participant 导入通讯录页面 as import_contact

main ->add_member:点击添加成员

main ->contact:点击通讯录

contact ->add_member:点击添加成员

add_member ->contact:保存新成员

contact ->contact:检查成员

contact ->add_department:点击+，选择“添加部门”

add_department -> contact:保存新部门

contact ->contact:检查部门

main -> import_contact:点击导入通讯录

import_contact ->contact:上传通讯录

contact ->contact:检查部门和成员

contact ->import_contact:点击批量导入，选择文件导入

import_contact ->contact:上传通讯录

contact ->contact:检查部门和成员

@enduml